# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/WORK/afe7700_xilinx/rtl/pll_test/pll_test.xci
# IP: The module: 'pll_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_test/pll_test_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_test'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_test/pll_test.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_test/pll_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/WORK/afe7700_xilinx/rtl/pll_test/pll_test.xci
# IP: The module: 'pll_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_test/pll_test_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_test/pll_test.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_test/pll_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
