# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/WORK/afe7700_xilinx/rtl/fifo_elastic_xilinx/fifo_elastic_xilinx.xci
# IP: The module: 'fifo_elastic_xilinx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WORK/afe7700_xilinx/rtl/fifo_elastic_xilinx/fifo_elastic_xilinx.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_elastic_xilinx'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/WORK/afe7700_xilinx/rtl/fifo_elastic_xilinx/fifo_elastic_xilinx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_elastic_xilinx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/WORK/afe7700_xilinx/rtl/fifo_elastic_xilinx/fifo_elastic_xilinx.xci
# IP: The module: 'fifo_elastic_xilinx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WORK/afe7700_xilinx/rtl/fifo_elastic_xilinx/fifo_elastic_xilinx.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_elastic_xilinx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/WORK/afe7700_xilinx/rtl/fifo_elastic_xilinx/fifo_elastic_xilinx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_elastic_xilinx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
