# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/WORK/afe7700_xilinx/rtl/pll_main/pll_main.xci
# IP: The module: 'pll_main' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_main/pll_main_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_main'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_main/pll_main.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_main'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_main/pll_main_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_main'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/WORK/afe7700_xilinx/rtl/pll_main/pll_main.xci
# IP: The module: 'pll_main' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_main/pll_main_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_main'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_main/pll_main.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_main'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/WORK/afe7700_xilinx/rtl/pll_main/pll_main_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_main'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
